import { db, run, all } from './server/db.js';

const categoryData: Record<string, {icon: string, desc: string}> = {
  "Tecnología": { icon: "Laptop", desc: "Equipos, computadoras, móviles y gadgets de última generación." },
  "Videojuegos": { icon: "Gamepad2", desc: "Consolas, videojuegos físicos/digitales y accesorios gamer." },
  "Audio": { icon: "Headphones", desc: "Auriculares, altavoces, micrófonos y equipos de sonido profesional." },
  "Cámaras": { icon: "Camera", desc: "Cámaras fotográficas, lentes, drones y accesorios audiovisuales." },
  "Electrodomésticos": { icon: "Coffee", desc: "Neveras, estufas, microondas y equipos para el hogar." },
  "Seguridad": { icon: "ShieldCheck", desc: "Cámaras de vigilancia, alarmas, candados y sistemas de seguridad." },
  "Vehículos": { icon: "CarFront", desc: "Automóviles, camionetas, camiones y vehículos comerciales." },
  "Repuestos": { icon: "Wrench", desc: "Piezas, accesorios y repuestos para todo tipo de vehículos." },
  "Motocicletas": { icon: "Bike", desc: "Motos, pasolas, cascos y accesorios para motoristas." },
  "Maquinaria": { icon: "Tractor", desc: "Equipos pesados, maquinaria agrícola e industrial." },
  "Muebles": { icon: "Sofa", desc: "Juegos de sala, comedores, camas y decoración para el hogar." },
  "Ferretería": { icon: "Hammer", desc: "Herramientas, materiales de construcción y artículos ferreteros." },
  "Jardinería": { icon: "Flower2", desc: "Plantas, macetas, herramientas y mobiliario de exteriores." },
  "Mascotas": { icon: "Dog", desc: "Alimentos, accesorios, casas y artículos para animales." },
  "Inmuebles": { icon: "Home", desc: "Casas, apartamentos, terrenos y locales comerciales." },
  "Ropa": { icon: "Shirt", desc: "Prendas de vestir para hombre, mujer y niño, en todos los estilos." },
  "Calzado": { icon: "Footprints", desc: "Zapatos, tenis, botas y sandalias para todas las edades." },
  "Joyería": { icon: "Gem", desc: "Cadenas, anillos, relojes finos y accesorios de metales preciosos." },
  "Bolsos": { icon: "ShoppingBag", desc: "Carteras, mochilas, maletas y equipaje de viaje." },
  "Cosmética": { icon: "Sparkles", desc: "Maquillaje, cuidado de la piel y productos de belleza." },
  "Fitness": { icon: "Dumbbell", desc: "Equipos de gimnasio, pesas y accesorios para ejercicio." },
  "Ciclismo": { icon: "Bike", desc: "Bicicletas, cascos, ropa deportiva y accesorios para ciclistas." },
  "Deportes": { icon: "Trophy", desc: "Artículos y uniformes deportivos." },
  "Camping": { icon: "Tent", desc: "Casas de campaña, linternas, sleeping bags y equipo al aire libre." },
  "Libros": { icon: "BookOpen", desc: "Literatura, textos escolares, revistas y cómics." },
  "Instrumentos": { icon: "Music", desc: "Guitarras, pianos, percusión y equipos musicales." },
  "Arte": { icon: "Palette", desc: "Cuadros, pinturas, esculturas y suministros artísticos." },
  "Coleccionables": { icon: "Medal", desc: "Cartas, monedas, figuras de acción y objetos de colección." },
  "Juguetes": { icon: "Puzzle", desc: "Juegos de mesa, muñecas, carritos y entretenimiento infantil." },
  "Alimentos": { icon: "Apple", desc: "Comestibles, frutas, verduras, carnes y productos de despensa." },
  "Bebidas": { icon: "Coffee", desc: "Refrescos, jugos, aguas y bebidas de todo tipo." },
  "Suplementos": { icon: "Pill", desc: "Proteínas, vitaminas, creatina y nutrición deportiva." },
  "Repostería": { icon: "Cake", desc: "Dulces, bizcochos, postres e ingredientes para hornear." },
  "Plomería": { icon: "Droplet", desc: "Tubos, grifos, inodoros y herramientas de fontanería." },
  "Electricidad": { icon: "Zap", desc: "Cables, bombillos, breakers y suministros eléctricos." },
  "Carpintería": { icon: "Hammer", desc: "Maderas, clavos, barnices y herramientas para carpinteros." },
  "Limpieza": { icon: "SprayCan", desc: "Detergentes, escobas, desinfectantes y artículos de aseo." },
  "Tutorías": { icon: "GraduationCap", desc: "Clases particulares, asesorías académicas y cursos cortos." },
  "Mudanzas": { icon: "Truck", desc: "Servicios de acarreo, transporte y mudanzas residenciales." },
  "Préstamos": { icon: "Banknote", desc: "Servicios financieros, préstamos personales y créditos." },
  "Seguros": { icon: "Shield", desc: "Pólizas de vida, vehículo, salud y propiedades." },
  "Asesoría": { icon: "Briefcase", desc: "Consultoría legal, financiera, migratoria y de negocios." },
  "Empleos": { icon: "Users", desc: "Ofertas de trabajo, vacantes y servicios profesionales." },
  "Químicos": { icon: "FlaskConical", desc: "Productos químicos industriales, limpieza pesada y laboratorio." },
  "Papelería": { icon: "Paperclip", desc: "Cuadernos, lapiceros, hojas y útiles escolares/de oficina." },
  "Embalajes": { icon: "Package", desc: "Cajas de cartón, cintas, plásticos de burbujas y empaques." },
  "Herramientas": { icon: "Wrench", desc: "Herramientas manuales, eléctricas y maquinaria ligera." },
  "Software": { icon: "Code", desc: "Sistemas informáticos, licencias, antivirus y apps." },
  "Entradas": { icon: "Ticket", desc: "Boletas para conciertos, cines, teatros y eventos deportivos." },
  "Catering": { icon: "ChefHat", desc: "Servicio de buffet, picaderas y banquetes para eventos." },
  "Telefonía": { icon: "Phone", desc: "Planes de internet, líneas telefónicas y servicios móviles." },
  "Relojería": { icon: "Watch", desc: "Relojes de pulsera, de pared, correas y mantenimiento." },
  "Computación": { icon: "Monitor", desc: "PCs de escritorio, monitores, teclados y componentes." },
  "Iluminación": { icon: "Lightbulb", desc: "Lámparas, focos LED, tiras luminosas y candelabros." },
  "Climatización": { icon: "ThermometerSnowflake", desc: "Aires acondicionados, abanicos, extractores y calefactores." },
  "Llantas": { icon: "Circle", desc: "Gomas y llantas para autos, camionetas y camiones." },
  "Neumáticos": { icon: "Circle", desc: "Neumáticos nuevos y usados de diversas marcas y tamaños." },
  "Bicicletas": { icon: "Bike", desc: "BMX, montañeras, ruteras y bicicletas para niños." },
  "Perfumería": { icon: "Droplet", desc: "Perfumes, colonias y fragancias para hombre y mujer." },
  "Lencería": { icon: "Shirt", desc: "Ropa interior femenina, pijamas y prendas íntimas." },
  "Bisutería": { icon: "Gem", desc: "Collares, pulseras, aretes y accesorios de moda." },
  "Óptica": { icon: "Glasses", desc: "Lentes de sol, monturas, lentes de contacto y estuches." },
  "Cristalería": { icon: "GlassWater", desc: "Vasos, copas, espejos, puertas y ventanas de cristal." },
  "Vajilla": { icon: "Utensils", desc: "Platos, tazones, cubiertos y sets para la mesa." },
  "Tapicería": { icon: "Scissors", desc: "Telas, forros para muebles, interiores de vehículos." },
  "Colchones": { icon: "Bed", desc: "Colchones ortopédicos, bases para cama y almohadas." },
  "Antigüedades": { icon: "Clock", desc: "Muebles clásicos, artículos vintage y piezas históricas." },
  "Artesanías": { icon: "Brush", desc: "Creaciones manuales, decoraciones locales y souvenirs." },
  "Pinturas": { icon: "PaintRoller", desc: "Pintura acrílica, brochas, rodillos y esmaltes." },
  "Esculturas": { icon: "Mountain", desc: "Obras talladas en madera, piedra, metal o arcilla." },
  "Cómics": { icon: "Book", desc: "Historietas, mangas, novelas gráficas y ediciones especiales." },
  "Música": { icon: "Disc", desc: "Discos de vinilo, CDs, cassettes y reproductores clásicos." },
  "Películas": { icon: "Film", desc: "DVDs, Blu-rays, cintas VHS y colecciones cinematográficas." },
  "Coleccionismo": { icon: "Archive", desc: "Sellos, billetes antiguos, tarjetas y rarezas de colección." },
  "Caza": { icon: "Crosshair", desc: "Equipos de precisión, camuflaje y artículos de supervivencia." },
  "Pesca": { icon: "Fish", desc: "Cañas de pescar, anzuelos, hilos, redes y carnadas." },
  "Senderismo": { icon: "Map", desc: "Botas de montaña, mochilas de camping y brújulas." },
  "Gimnasios": { icon: "Dumbbell", desc: "Suscripciones, pases y servicios de entrenamiento personal." },
  "Nutrición": { icon: "Apple", desc: "Dietas personalizadas, batidos saludables y asesoría nutricional." },
  "Licorería": { icon: "Wine", desc: "Vinos, whiskys, rones, cervezas y bebidas espirituosas." },
  "Charcutería": { icon: "Beef", desc: "Quesos, jamones, embutidos y productos gourmet." },
  "Panadería": { icon: "Croissant", desc: "Pan fresco, galletas, masitas y productos horneados." },
  "Heladería": { icon: "IceCream", desc: "Helados, paletas, postres fríos y toppings variados." },
  "Lavandería": { icon: "Shirt", desc: "Servicio de lavado, planchado y tintorería para ropa." },
  "Sastrería": { icon: "Scissors", desc: "Arreglos de ropa, confección a la medida y costura." },
  "Peluquería": { icon: "Scissors", desc: "Cortes de pelo, tintes, secado y tratamientos capilares." },
  "Barbería": { icon: "Scissors", desc: "Cortes masculinos, arreglo de barba y cuidado personal." },
  "Veterinaria": { icon: "Stethoscope", desc: "Consultas, vacunas y atención médica para mascotas." },
  "Guarderías": { icon: "Baby", desc: "Cuidado infantil, preescolar y estimulación temprana." },
  "Fotografía": { icon: "Camera", desc: "Sesiones de fotos, cobertura de eventos y álbumes." },
  "Imprenta": { icon: "Printer", desc: "Tarjetas, afiches, sublimación y material publicitario." },
  "Contabilidad": { icon: "Calculator", desc: "Servicios contables, impuestos y declaraciones." },
  "Notaría": { icon: "FileSignature", desc: "Trámites legales, certificaciones y firmas de abogados." },
  "Logística": { icon: "Truck", desc: "Envíos, aduanas, transporte de carga e importaciones." },
  "Almacenaje": { icon: "Box", desc: "Alquiler de depósitos, trasteros y guardamuebles." },
  "Envases": { icon: "Package", desc: "Frascos, botellas, fundas y recipientes para negocios." },
  "Maternidad": { icon: "Baby", desc: "Ropa para embarazadas, biberones, cunas y accesorios." },
  "Cotillón": { icon: "PartyPopper", desc: "Artículos para fiestas, globos, velas y decoración." },
  "Hospedaje": { icon: "Hotel", desc: "Hoteles, moteles, cabañas y habitaciones de alquiler." },
  "Turismo": { icon: "Compass", desc: "Excursiones, pasajes, tours y paquetes vacacionales." }
};

async function update() {
  try { await run("ALTER TABLE vuttik_categories ADD COLUMN description TEXT"); } catch (e) {}

  for (const [name, info] of Object.entries(categoryData)) {
    await run("UPDATE vuttik_categories SET icon = ?, description = ? WHERE name = ?", [info.icon, info.desc, name]);
  }
  console.log('Categories updated!');
}
update();
