export const COUNTRIES = [
  { code: 'DO', dialCode: '+1', name: 'República Dominicana', flag: '🇩🇴' },
  { code: 'US', dialCode: '+1', name: 'Estados Unidos', flag: '🇺🇸' },
  { code: 'AF', dialCode: '+93', name: 'Afganistán', flag: '🇦🇫' },
  { code: 'AL', dialCode: '+355', name: 'Albania', flag: '🇦🇱' },
  { code: 'DE', dialCode: '+49', name: 'Alemania', flag: '🇩🇪' },
  { code: 'AD', dialCode: '+376', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', dialCode: '+244', name: 'Angola', flag: '🇦🇴' },
  { code: 'AI', dialCode: '+1', name: 'Anguila', flag: '🇦🇮' },
  { code: 'AQ', dialCode: '+672', name: 'Antártida', flag: '🇦🇶' },
  { code: 'AG', dialCode: '+1', name: 'Antigua y Barbuda', flag: '🇦🇬' },
  { code: 'SA', dialCode: '+966', name: 'Arabia Saudita', flag: '🇸🇦' },
  { code: 'DZ', dialCode: '+213', name: 'Argelia', flag: '🇩🇿' },
  { code: 'AR', dialCode: '+54', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', dialCode: '+374', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AW', dialCode: '+297', name: 'Aruba', flag: '🇦🇼' },
  { code: 'AU', dialCode: '+61', name: 'Australia', flag: '🇦🇺' },
  { code: 'AT', dialCode: '+43', name: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', dialCode: '+994', name: 'Azerbaiyán', flag: '🇦🇿' },
  { code: 'BS', dialCode: '+1', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', dialCode: '+973', name: 'Bahréin', flag: '🇧🇭' },
  { code: 'BD', dialCode: '+880', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', dialCode: '+1', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BE', dialCode: '+32', name: 'Bélgica', flag: '🇧🇪' },
  { code: 'BZ', dialCode: '+501', name: 'Belice', flag: '🇧🇿' },
  { code: 'BJ', dialCode: '+229', name: 'Benín', flag: '🇧🇯' },
  { code: 'BM', dialCode: '+1', name: 'Bermudas', flag: '🇧🇲' },
  { code: 'BY', dialCode: '+375', name: 'Bielorrusia', flag: '🇧🇾' },
  { code: 'BO', dialCode: '+591', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', dialCode: '+387', name: 'Bosnia y Herzegovina', flag: '🇧🇦' },
  { code: 'BW', dialCode: '+267', name: 'Botsuana', flag: '🇧🇼' },
  { code: 'BR', dialCode: '+55', name: 'Brasil', flag: '🇧🇷' },
  { code: 'BN', dialCode: '+673', name: 'Brunéi', flag: '🇧🇳' },
  { code: 'BG', dialCode: '+359', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', dialCode: '+226', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', dialCode: '+257', name: 'Burundi', flag: '🇧🇮' },
  { code: 'BT', dialCode: '+975', name: 'Bután', flag: '🇧🇹' },
  { code: 'CV', dialCode: '+238', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'KH', dialCode: '+855', name: 'Camboya', flag: '🇰🇭' },
  { code: 'CM', dialCode: '+237', name: 'Camerún', flag: '🇨🇲' },
  { code: 'CA', dialCode: '+1', name: 'Canadá', flag: '🇨🇦' },
  { code: 'QA', dialCode: '+974', name: 'Catar', flag: '🇶🇦' },
  { code: 'TD', dialCode: '+235', name: 'Chad', flag: '🇹🇩' },
  { code: 'CL', dialCode: '+56', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', dialCode: '+86', name: 'China', flag: '🇨🇳' },
  { code: 'CY', dialCode: '+357', name: 'Chipre', flag: '🇨🇾' },
  { code: 'CO', dialCode: '+57', name: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', dialCode: '+269', name: 'Comoras', flag: '🇰🇲' },
  { code: 'CG', dialCode: '+242', name: 'Congo', flag: '🇨🇬' },
  { code: 'KP', dialCode: '+850', name: 'Corea del Norte', flag: '🇰🇵' },
  { code: 'KR', dialCode: '+82', name: 'Corea del Sur', flag: '🇰🇷' },
  { code: 'CR', dialCode: '+506', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', dialCode: '+225', name: 'Costa de Marfil', flag: '🇨🇮' },
  { code: 'HR', dialCode: '+385', name: 'Croacia', flag: '🇭🇷' },
  { code: 'CU', dialCode: '+53', name: 'Cuba', flag: '🇨🇺' },
  { code: 'DK', dialCode: '+45', name: 'Dinamarca', flag: '🇩🇰' },
  { code: 'EC', dialCode: '+593', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', dialCode: '+20', name: 'Egipto', flag: '🇪🇬' },
  { code: 'SV', dialCode: '+503', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'AE', dialCode: '+971', name: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { code: 'ER', dialCode: '+291', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'SK', dialCode: '+421', name: 'Eslovaquia', flag: '🇸🇰' },
  { code: 'SI', dialCode: '+386', name: 'Eslovenia', flag: '🇸🇮' },
  { code: 'ES', dialCode: '+34', name: 'España', flag: '🇪🇸' },
  { code: 'EE', dialCode: '+372', name: 'Estonia', flag: '🇪🇪' },
  { code: 'ET', dialCode: '+251', name: 'Etiopía', flag: '🇪🇹' },
  { code: 'PH', dialCode: '+63', name: 'Filipinas', flag: '🇵🇭' },
  { code: 'FI', dialCode: '+358', name: 'Finlandia', flag: '🇫🇮' },
  { code: 'FJ', dialCode: '+679', name: 'Fiyi', flag: '🇫🇯' },
  { code: 'FR', dialCode: '+33', name: 'Francia', flag: '🇫🇷' },
  { code: 'GA', dialCode: '+241', name: 'Gabón', flag: '🇬🇦' },
  { code: 'GM', dialCode: '+220', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', dialCode: '+995', name: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', dialCode: '+233', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GI', dialCode: '+350', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GD', dialCode: '+1', name: 'Granada', flag: '🇬🇩' },
  { code: 'GR', dialCode: '+30', name: 'Grecia', flag: '🇬🇷' },
  { code: 'GL', dialCode: '+299', name: 'Groenlandia', flag: '🇬🇱' },
  { code: 'GT', dialCode: '+502', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', dialCode: '+224', name: 'Guinea', flag: '🇬🇳' },
  { code: 'GQ', dialCode: '+240', name: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { code: 'GY', dialCode: '+592', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', dialCode: '+509', name: 'Haití', flag: '🇭🇹' },
  { code: 'HN', dialCode: '+504', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HK', dialCode: '+852', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'HU', dialCode: '+36', name: 'Hungría', flag: '🇭🇺' },
  { code: 'IN', dialCode: '+91', name: 'India', flag: '🇮🇳' },
  { code: 'ID', dialCode: '+62', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IQ', dialCode: '+964', name: 'Irak', flag: '🇮🇶' },
  { code: 'IR', dialCode: '+98', name: 'Irán', flag: '🇮🇷' },
  { code: 'IE', dialCode: '+353', name: 'Irlanda', flag: '🇮🇪' },
  { code: 'IS', dialCode: '+354', name: 'Islandia', flag: '🇮🇸' },
  { code: 'IL', dialCode: '+972', name: 'Israel', flag: '🇮🇱' },
  { code: 'IT', dialCode: '+39', name: 'Italia', flag: '🇮🇹' },
  { code: 'JM', dialCode: '+1', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', dialCode: '+81', name: 'Japón', flag: '🇯🇵' },
  { code: 'JO', dialCode: '+962', name: 'Jordania', flag: '🇯🇴' },
  { code: 'KZ', dialCode: '+7', name: 'Kazajistán', flag: '🇰🇿' },
  { code: 'KE', dialCode: '+254', name: 'Kenia', flag: '🇰🇪' },
  { code: 'KG', dialCode: '+996', name: 'Kirguistán', flag: '🇰🇬' },
  { code: 'KW', dialCode: '+965', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'LA', dialCode: '+856', name: 'Laos', flag: '🇱🇦' },
  { code: 'LB', dialCode: '+961', name: 'Líbano', flag: '🇱🇧' },
  { code: 'LR', dialCode: '+231', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', dialCode: '+218', name: 'Libia', flag: '🇱🇾' },
  { code: 'LI', dialCode: '+423', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', dialCode: '+370', name: 'Lituania', flag: '🇱🇹' },
  { code: 'LU', dialCode: '+352', name: 'Luxemburgo', flag: '🇱🇺' },
  { code: 'MG', dialCode: '+261', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MY', dialCode: '+60', name: 'Malasia', flag: '🇲🇾' },
  { code: 'MW', dialCode: '+265', name: 'Malaui', flag: '🇲🇼' },
  { code: 'MV', dialCode: '+960', name: 'Maldivas', flag: '🇲🇻' },
  { code: 'ML', dialCode: '+223', name: 'Malí', flag: '🇲🇱' },
  { code: 'MT', dialCode: '+356', name: 'Malta', flag: '🇲🇹' },
  { code: 'MA', dialCode: '+212', name: 'Marruecos', flag: '🇲🇦' },
  { code: 'MU', dialCode: '+230', name: 'Mauricio', flag: '🇲🇺' },
  { code: 'MR', dialCode: '+222', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'MX', dialCode: '+52', name: 'México', flag: '🇲🇽' },
  { code: 'MD', dialCode: '+373', name: 'Moldavia', flag: '🇲🇩' },
  { code: 'MC', dialCode: '+377', name: 'Mónaco', flag: '🇲🇨' },
  { code: 'MN', dialCode: '+976', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', dialCode: '+382', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MZ', dialCode: '+258', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', dialCode: '+95', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', dialCode: '+264', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NP', dialCode: '+977', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NI', dialCode: '+505', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', dialCode: '+227', name: 'Níger', flag: '🇳🇪' },
  { code: 'NG', dialCode: '+234', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'NO', dialCode: '+47', name: 'Noruega', flag: '🇳🇴' },
  { code: 'NZ', dialCode: '+64', name: 'Nueva Zelanda', flag: '🇳🇿' },
  { code: 'OM', dialCode: '+968', name: 'Omán', flag: '🇴🇲' },
  { code: 'NL', dialCode: '+31', name: 'Países Bajos', flag: '🇳🇱' },
  { code: 'PK', dialCode: '+92', name: 'Pakistán', flag: '🇵🇰' },
  { code: 'PA', dialCode: '+507', name: 'Panamá', flag: '🇵🇦' },
  { code: 'PY', dialCode: '+595', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', dialCode: '+51', name: 'Perú', flag: '🇵🇪' },
  { code: 'PL', dialCode: '+48', name: 'Polonia', flag: '🇵🇱' },
  { code: 'PT', dialCode: '+351', name: 'Portugal', flag: '🇵🇹' },
  { code: 'PR', dialCode: '+1', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'GB', dialCode: '+44', name: 'Reino Unido', flag: '🇬🇧' },
  { code: 'CF', dialCode: '+236', name: 'República Centroafricana', flag: '🇨🇫' },
  { code: 'CZ', dialCode: '+420', name: 'República Checa', flag: '🇨🇿' },
  { code: 'CD', dialCode: '+243', name: 'República Democrática del Congo', flag: '🇨🇩' },
  { code: 'RW', dialCode: '+250', name: 'Ruanda', flag: '🇷🇼' },
  { code: 'RO', dialCode: '+40', name: 'Rumanía', flag: '🇷🇴' },
  { code: 'RU', dialCode: '+7', name: 'Rusia', flag: '🇷🇺' },
  { code: 'SN', dialCode: '+221', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', dialCode: '+381', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SG', dialCode: '+65', name: 'Singapur', flag: '🇸🇬' },
  { code: 'SY', dialCode: '+963', name: 'Siria', flag: '🇸🇾' },
  { code: 'SO', dialCode: '+252', name: 'Somalia', flag: '🇸🇴' },
  { code: 'LK', dialCode: '+94', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'ZA', dialCode: '+27', name: 'Sudáfrica', flag: '🇿🇦' },
  { code: 'SD', dialCode: '+249', name: 'Sudán', flag: '🇸🇩' },
  { code: 'SE', dialCode: '+46', name: 'Suecia', flag: '🇸🇪' },
  { code: 'CH', dialCode: '+41', name: 'Suiza', flag: '🇨🇭' },
  { code: 'TH', dialCode: '+66', name: 'Tailandia', flag: '🇹🇭' },
  { code: 'TW', dialCode: '+886', name: 'Taiwán', flag: '🇹🇼' },
  { code: 'TZ', dialCode: '+255', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'TJ', dialCode: '+992', name: 'Tayikistán', flag: '🇹🇯' },
  { code: 'TG', dialCode: '+228', name: 'Togo', flag: '🇹🇬' },
  { code: 'TN', dialCode: '+216', name: 'Túnez', flag: '🇹🇳' },
  { code: 'TR', dialCode: '+90', name: 'Turquía', flag: '🇹🇷' },
  { code: 'UA', dialCode: '+380', name: 'Ucrania', flag: '🇺🇦' },
  { code: 'UG', dialCode: '+256', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UY', dialCode: '+598', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', dialCode: '+998', name: 'Uzbekistán', flag: '🇺🇿' },
  { code: 'VE', dialCode: '+58', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', dialCode: '+84', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', dialCode: '+967', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', dialCode: '+260', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', dialCode: '+263', name: 'Zimbabue', flag: '🇿🇼' }
];
