name: Test Node

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test
        run: |
          ssh -o ConnectTimeout=15 -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /home/sinagjwx/domains/vuttik.com/server && export NODE_HOME="/home/sinagjwx/nodejs" && export PATH="$NODE_HOME/bin:/usr/local/bin:/usr/bin:/bin:$PATH" && export NODE_ENV=production && node index.js'
